#+OPTIONS: toc:nil
# #+LaTeX_CLASS: koma-article 

#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation,aspectratio=169]
#+OPTIONS: H:2

#+LaTex_HEADER: \usepackage{khpreamble}
#+LaTex_HEADER: \usepackage{amssymb}
#+LaTex_HEADER: \usepgfplotslibrary{groupplots}

#+LaTex_HEADER: \newcommand*{\shift}{\operatorname{q}}
#+LaTex_HEADER: \DeclareMathSymbol{\Omega}{\mathalpha}{letters}{"0A}% italics
#+LaTex_HEADER: \DeclareMathSymbol{\varOmega}{\mathalpha}{operators}{"0A}% upright
#+LaTex_HEADER: \providecommand*{\upOmega}{\varOmega}% for siunitx
#+LaTex_HEADER: \usepackage[binary-units=true]{siunitx}
#+LaTex_HEADER: \usepackage{circuitikz}
#+LaTex_HEADER: \usetikzlibrary{calc}


#+title: Espacio de estados  - polos, función de transferencia
#+author: Kjartan Halvorsen
#+date: 2021-06-03

* What do I want the students to understand?			   :noexport:
  - Characteristic equation
  - Solution
    
* Which activities will the students do?			   :noexport:
  - Fill in the blanks
  - Exercises on Canvas

* Mass-spring-damper, acceleration as output
** Masa-resorte-amortiguador
#+begin_center
\includegraphics[width=0.2\linewidth]{../../figures/mass-spring-damper.png}
#+end_center

\( x = \begin{bmatrix} X & \dot{X} \end{bmatrix}\). La aceleración \(\ddot{X}\) como señal de salida.

   \begin{center}
   \Large
   \begin{align*}
     \dot{x} &= \overbrace{\begin{bmatrix} \textcolor{red!80!black}{0} & \textcolor{red!80!black}{0}\\ \textcolor{red!80!black}{-\frac{k}{m}}  & \textcolor{red!80!black}{-\frac{c}{m}} \end{bmatrix}}^A x  + \overbrace{\begin{bmatrix} \textcolor{red!80!black}{0} \\ \textcolor{red!80!black}{\frac{1}{m}} \end{bmatrix}}^B  u \\
          y &=  \underbrace{\begin{bmatrix} \textcolor{white}{-\frac{k}{m}}  & \textcolor{white}{-\frac{c}{m}} \end{bmatrix}}_C x + \underbrace{\begin{bmatrix} \textcolor{white}{\frac{1}{m}} \end{bmatrix}}_D u
   \end{align*}
   
   \end{center}


** Masa-resorte-amortiguador
#+begin_center
\includegraphics[width=0.2\linewidth]{../../figures/mass-spring-damper.png}
#+end_center

\( x = \begin{bmatrix} X & \dot{X} \end{bmatrix}\). La aceleración \(\ddot{X}\) como señal de salida.

   \begin{center}
   \Large
   \begin{align*}
     \dot{x} &= \overbrace{\begin{bmatrix} \textcolor{red!80!black}{0} & \textcolor{red!80!black}{0}\\ \textcolor{red!80!black}{-\frac{k}{m}}  & \textcolor{red!80!black}{-\frac{c}{m}} \end{bmatrix}}^A x  + \overbrace{\begin{bmatrix} \textcolor{red!80!black}{0} \\ \textcolor{red!80!black}{\frac{1}{m}} \end{bmatrix}}^B  u \\
          y &=  \underbrace{\begin{bmatrix} \textcolor{red!80!black}{-\frac{k}{m}}  & \textcolor{red!80!black}{-\frac{c}{m}} \end{bmatrix}}_C x + \underbrace{\begin{bmatrix} \textcolor{red!80!black}{\frac{1}{m}} \end{bmatrix}}_D u
   \end{align*}
   
   \end{center}


* Canonical forms

** Formas canonicas

- Forma controlable
- Forma observable

*** Recurso 
[[https://lpsa.swarthmore.edu/Representations/SysRepTransformations/TF2SS.html][https://lpsa.swarthmore.edu/Representations/SysRepTransformations/TF2SS.html]]
    
* Estabilidad

** Estabilidad
   
   La solución homógena de \(\dot{x} = Ax\)  se puede escribir
   \[ x(t) = \mathrm{e}^{\lambda_1 t}\alpha_1v_1 + \mathrm{e}^{\lambda_2 t}\alpha_2v_2 + \cdots + \mathrm{e}^{\lambda_n t}\alpha_nv_n,\]
   donde \(\lambda_1\), \(\lambda_2\), \(\ldots\), \(\lambda_n\) son los *eigenvalores* de \(A\). 

   Estabilidad requiere que *cada una* de las funciones exponenciales va hacia cero.
   \[\Rightarrow \qquad \mathrm{Re}\{\lambda_i\} < 0, \; \forall i=1,2,3\ldots, n\]

Los eigenvalores de $A$ son los *polos* del sistema.

** Los eigenvalores
   \(\lambda\) y \(v\) es un par de eigenvalor y eigenvector de la matriz $A$ si
   \[Av = \lambda v\]
#+BEAMER: \pause
    \[ \lambda v - Av = 0\]
#+BEAMER: \pause
    \[ (\lambda I - A)v = 0\]
#+BEAMER: \pause
   Para que la ecuación tenga soluciones no-triviales
    \[ \det (\lambda I - A) = 0 \quad \leftarrow \text{\alert{Ecuación característica}}\]
    
   
* Modelo compartamental

** De espacio de estados a función de transferencia

** Modelo compartimental
   #+begin_export latex
    \small
   \begin{columns}
     \begin{column}{0.5\linewidth}
       \begin{center}
	 \begin{tikzpicture}[scale=0.8, transform shape,
	   compartment/.style={rounded corners=5mm, minimum height=14mm, minimum width=16mm},
	   node distance=46mm,
	   ]

	   \node[compartment, draw=red, ] (comp1) {$V_1, c_1$};
	   \node[compartment, right of=comp1, draw=olive,] (comp2) {$V_2, c_2$};

	   \node[coordinate, above of=comp1, node distance=20mm] (input) {};
	   \node[coordinate, below of=comp1, node distance=20mm] (output) {};

	   \draw[->, double] (input) -- node[right]{$c_{i}Q_i$} (comp1);
	   \draw[->, double] (comp1) -- node[right]{$c_{1}Q_o$} (output);
	   \draw[<->, double] (comp1) -- node[above]{$(c_{2}-c_1)Q$} (comp2);

	 \end{tikzpicture}
       \end{center}

     \end{column}
     \begin{column}{0.5\linewidth}
       \begin{equation*}
	 \begin{aligned}
	   V_1\frac{dc_1}{dt} &= Q(c_2-c_1) - Q_{o}c_1 + Q_ic_{i}, \quad  & c_1 \geq 0 \\
	   V_2\frac{dc_2}{dt} &= Q(c_1-c_2),  & c_2 \geq 0,
	 \end{aligned}
       \end{equation*}
     \end{column}
   \end{columns}

   \begin{center}
   \Large
   \begin{align*}
     \dot{x} &= \overbrace{\begin{bmatrix} \textcolor{red!80!black}{-\frac{Q+Q_o}{V_1}}  & \textcolor{red!80!black}{\frac{Q}{V_1}}\\
                 \textcolor{red!80!black}{\frac{Q}{V_2}}  & \textcolor{red!80!black}{-\frac{Q}{V_2}}\end{bmatrix}}^A \begin{bmatrix} {x_1}\\ {x_2}\end{bmatrix}  + \overbrace{\begin{bmatrix} \textcolor{red!80!black}{\frac{1}{V_1}} \\ \textcolor{red!80!black}{0} \end{bmatrix}}^B  u \\
          y &=  \underbrace{\begin{bmatrix} \textcolor{red!80!black}{1} &  \textcolor{red!80!black}{0}\end{bmatrix}}_C \begin{bmatrix} x_1\\ x_2\end{bmatrix}
   \end{align*}
   
   \end{center}
   #+end_export





** De espacio de estados a función de transferencia

   \footnotesize

   \begin{align*}
     \dot{x} &= \overbrace{\begin{bmatrix} \textcolor{red!80!black}{-\frac{Q+Q_o}{V_1}}  & \textcolor{red!80!black}{\frac{Q}{V_1}}\\
                 \textcolor{red!80!black}{\frac{Q}{V_2}}  & \textcolor{red!80!black}{-\frac{Q}{V_2}}\end{bmatrix}}^A \begin{bmatrix} {x_1}\\ {x_2}\end{bmatrix}  + \overbrace{\begin{bmatrix} \textcolor{red!80!black}{\frac{1}{V_1}} \\ \textcolor{red!80!black}{0} \end{bmatrix}}^B  u  = Ax + Bu\\
          y &=  \underbrace{\begin{bmatrix} \textcolor{red!80!black}{1} &  \textcolor{red!80!black}{0}\end{bmatrix}}_C \begin{bmatrix} x_1\\ x_2\end{bmatrix} = Cx
   \end{align*}

   Aplicando la transformada de Laplace
   \begin{align*}
   sX - x(0) &= AX + BU\\
   Y &= CX
   \end{align*}
   #+BEAMER: \pause
   Despejando $X(s)$
   \begin{align*}
   X(s) &= (sI-A)^{-1}x(0) + (sI-A)^{-1}BU(s)\\
   Y(s) &= C\big((sI-A)^{-1}x(0) + (sI-A)^{-1}BU(s)\big)\\
        & = \underbrace{C(sI-A)^{-1}x(0)}_{\text{\alert{Respuesta transitoria}}} + \underbrace{C(sI-A)^{-1}B}_{\text{\alert{Función de transf.}}}U(s)
   \end{align*}
   

** Transformada de Laplace de una función exponencial
    
    \[F(s) = \laplace{f(t)} = \int_0^\infty f(t)\mexp{-st}dt\]
   #+BEAMER: \pause
    \[\laplace{\mexp{pt}} = \int_0^\infty \mexp{pt}\mexp{-st}dt = \int_0^\infty \mexp{-(s-p)t}dt = \frac{1}{s-p} = (s-p)^{-1}, \quad \mathrm{Re}\{s\} > \mathrm{Re}\{p\} \]


** Solución homógena de sistemas en espacio de estados
   \small
   \begin{align*}
   \dot{x} &= Ax, \qquad x(0) = x_0\\
    sX(s) - x(0) &= AX(s)
    \end{align*}
   #+BEAMER: \pause

*** Solución en dominio de Laplace
   :PROPERTIES:
   :beamer_col: 0.5
   :beamer_env: block
   :END:

   \[X(s) = (sI-A)^{-1}x(0)\]

   #+BEAMER: \pause

*** Solución en dominio de tiempo
   :PROPERTIES:
   :beamer_col: 0.5
   :beamer_env: block
   :END:

   \[ x(t) = \Phi(t)x(0) = \mathrm{e}^{At}x(0)\]

   Donde  $\Phi:\,\mathbb{R} \rightarrow \mathbb{R}^{n\times n}$ \[\Phi(t)=\mathrm{e}^{At} = I + tA + \frac{t^2}{2!}A^2 + \frac{t^3}{3!}A^3 + \cdots\] 

** La transformada de Laplace de la exponencial de una matriz

   \[ f(t)=\mathrm{e}^{At} \qquad \overset{\mathcal{L}}{\longleftrightarrow} \qquad F(s) = (sI-A)^{-1} \]

      #+BEAMER: \pause

      \[(sI-A)^{-1} = \frac{1}{\det (sI-A)} \, \text{adj}\, (sI-A) \]

      \(\det (sI-A)\) es un polinomio en \(s\), llamado \alert{polinomio característico}. Sus raíces, es decir las soluciones de la \alert{ecuación característica}
      \[ \det(sI-A) = 0\]
      son los \alert{polos} del sistema y los eigenvalores de \(A\).

** De espacio de estados a función de transferencia

   \footnotesize

   \begin{align*}
     \dot{x} &= \overbrace{\begin{bmatrix} \textcolor{red!80!black}{-\frac{Q+Q_o}{V_1}}  & \textcolor{red!80!black}{\frac{Q}{V_1}} \\
                 \textcolor{red!80!black}{\frac{Q}{V_2}}  & \textcolor{red!80!black}{-\frac{Q}{V_2}}\end{bmatrix}}^A \begin{bmatrix} {x_1}\\ {x_2}\end{bmatrix}  + \overbrace{\begin{bmatrix} \textcolor{red!80!black}{\frac{1}{V_1}} \\ \textcolor{red!80!black}{0} \end{bmatrix}}^B  u
= \begin{bmatrix} \textcolor{red!80!black}{a}  & \textcolor{red!80!black}{b} \\
                 \textcolor{red!80!black}{c}  & \textcolor{red!80!black}{d}\end{bmatrix} x  + \begin{bmatrix} \textcolor{red!80!black}{b_1} \\ \textcolor{red!80!black}{0} \end{bmatrix} u, \qquad
          y =  \underbrace{\begin{bmatrix} \textcolor{red!80!black}{1} &  \textcolor{red!80!black}{0}\end{bmatrix}}_C x\\
   X(s) &= (sI-A)^{-1}x(0) + (sI-A)^{-1}BU(s)\\
   Y(s) &= \underbrace{C(sI-A)^{-1}x(0)}_{\text{\alert{Respuesta transitoria}}} + \underbrace{C(sI-A)^{-1}B}_{\text{\alert{Función de transf.}}}U(s)
   \end{align*}

#+BEAMER: \pause
   
*** \( (sI-A)^{-1}\)
   :PROPERTIES:
   :beamer_col: 0.5
   :END:

   \begin{align*}
    (sI-A)^{-1} &= \begin{bmatrix} s-a & -b\\-c & s-d\end{bmatrix}^{-1}\\
&=\frac{1}{\det (sI-A)} \, \text{adj}\, (sI-A)\\
         &= \frac{1}{(s-a)(s-d) - bc} \begin{bmatrix} s-d & b\\c & s-a \end{bmatrix}
	 \end{align*}

#+BEAMER: \pause

*** \( G(s) \)
   :PROPERTIES:
   :beamer_col: 0.5
   :END:

   \begin{align*}
   G(s) &= C(sI-A)^{-1}B\\
        &= \begin{bmatrix} \textcolor{red!80!black}{1} &  \textcolor{red!80!black}{0}\end{bmatrix} \frac{1}{(s-a)(s-d) - bc} \begin{bmatrix} s-d & b\\c & s-a \end{bmatrix} \begin{bmatrix} \textcolor{red!80!black}{b_1} \\ \textcolor{red!80!black}{0} \end{bmatrix}\\
       &=  \frac{\textcolor{white}{b_1(s-d)}}{\textcolor{white}{(s-a)(s-d) - bc}}
   \end{align*}


** De espacio de estados a función de transferencia

   \footnotesize

   \begin{align*}
     \dot{x} &= \overbrace{\begin{bmatrix} \textcolor{red!80!black}{-\frac{Q+Q_o}{V_1}}  & \textcolor{red!80!black}{\frac{Q}{V_1}} \\
                 \textcolor{red!80!black}{\frac{Q}{V_2}}  & \textcolor{red!80!black}{-\frac{Q}{V_2}}\end{bmatrix}}^A \begin{bmatrix} {x_1}\\ {x_2}\end{bmatrix}  + \overbrace{\begin{bmatrix} \textcolor{red!80!black}{\frac{1}{V_1}} \\ \textcolor{red!80!black}{0} \end{bmatrix}}^B  u
= \begin{bmatrix} \textcolor{red!80!black}{a}  & \textcolor{red!80!black}{b} \\
                 \textcolor{red!80!black}{c}  & \textcolor{red!80!black}{d}\end{bmatrix} x  + \begin{bmatrix} \textcolor{red!80!black}{b_1} \\ \textcolor{red!80!black}{0} \end{bmatrix} u, \qquad
          y =  \underbrace{\begin{bmatrix} \textcolor{red!80!black}{1} &  \textcolor{red!80!black}{0}\end{bmatrix}}_C x\\
   X(s) &= (sI-A)^{-1}x(0) + (sI-A)^{-1}BU(s)\\
   Y(s) &= \underbrace{C(sI-A)^{-1}x(0)}_{\text{\alert{Respuesta transitoria}}} + \underbrace{C(sI-A)^{-1}B}_{\text{\alert{Función de transf.}}}U(s)
   \end{align*}

   
*** \( (sI-A)^{-1}\)
   :PROPERTIES:
   :beamer_col: 0.5
   :END:

   \begin{align*}
    (sI-A)^{-1} &= \begin{bmatrix} s-a & -b\\-c & s-d\end{bmatrix}^{-1}\\
&=\frac{1}{\det (sI-A)} \, \text{adj}\, (sI-A)\\
         &= \frac{1}{(s-a)(s-d) - bc} \begin{bmatrix} s-d & b\\c & s-a \end{bmatrix}
	 \end{align*}


*** \( G(s) \)
   :PROPERTIES:
   :beamer_col: 0.5
   :END:

   \begin{align*}
   G(s) &= C(sI-A)^{-1}B\\
        &= \begin{bmatrix} \textcolor{red!80!black}{1} &  \textcolor{red!80!black}{0}\end{bmatrix} \frac{1}{(s-a)(s-d) - bc} \begin{bmatrix} s-d & b\\c & s-a \end{bmatrix} \begin{bmatrix} \textcolor{red!80!black}{b_1} \\ \textcolor{red!80!black}{0} \end{bmatrix}\\
       &=  \frac{\textcolor{black}{b_1(s-d)}}{\textcolor{black}{(s-a)(s-d) - bc}}
   \end{align*}
